### ISSUE TITLE
Use snippets and completions on Markdown files

### ISSUE THREAD

**Issue by jmml97** [SublimeText/LaTeXTools#1223]
Is there a way to enable all the LaTeX snippets and completions provided by LaTeXTools on Markdown files? With `pandoc` you can write LaTeX inside a Markdown file and generate a PDF later.

**Comment by r-stein** [comment]
You may edit the markdown syntax definition to add `text.tex.latex` as top level scope. This will enable all LaTeXTools features in the document.

**Comment by jmml97** [comment]
Thanks! I think snippets work now (I've tried `sec` for `\section{}` and `it` for `textit` and they worked fine). But the greek symbol completion doesn't seem to work. When I type _a_ for example and hit tab, Sublime cycles though all the Markdown snippets but I never get `\alpha`. Any ideas?

**Comment by r-stein** [comment]
Those are only enabled inside math environments. You can try to change the syntax definitions to also match match environments by adding the following to the main context:

```yaml
  main: # <- already present
    - include: scope:text.tex.latex#inline-math
    - include: scope:text.tex.latex#block-math
    # ....
```
This should also enable other LaTeXTools features like math preview.
