### ISSUE TITLE
How to change the color scheme for a specific command/environment

### ISSUE THREAD

**Issue by Awen0121** [SublimeText/LaTeXTools#1253]
Hi all,

I am having a problem that in the *.tex files there are too many `\todo`, which usually only serve as memo after these comments are implemented and these commands are very distracting when editing.
I am wondering if there is a simple workaround that enables me change their color to some not so distracting ones, or even make them invisible.

Thanks.

**Comment by r-stein** [comment]
`\todo` is highlighted as every other command and you want to disable the highlighting only for those todo commands?

**Comment by Awen0121** [comment]
Yes, exactly.
To be more specific, I want to change syntax coloring of `\todo` to comment color.

**Comment by r-stein** [comment]
Install PackageResourceViewer, open the file *LaTeX/LaTeX.sublime-syntax*, below the main context just add these lines:

```yaml
    - match: \\todo\s*{[^}]*}
      scope: comment.line.todo.latex
```

**Comment by Awen0121** [comment]
Hi, @r-stein , I am not sure if I understand you correctly.
I put it in the body of `main:`. Is that correct?
Nothing happened after I did this.
Perhaps you can explain a little bit?
I understand what `match:` do, but what about `scope:`?
Thanks.
```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: LaTeX
file_extensions:
  - tex
  - ltx
scope: text.tex.latex
contexts:
  prototype:
    - include: comments

  main:
    - include: unique-latex
    - include: packages
    - include: plain-tex
    - include: begin-end-commands
    - include: general-commands
    - include: global-braces
    - match: \\todo\s*{[^}]*}
      scope: comment.line.todo.latex
```

**Comment by r-stein** [comment]
You need to move it before `general-commands` like it to this:

```yaml
  main:
    - match: \\todo\s*{[^}]*}
      scope: comment.line.todo.latex
    - include: unique-latex
    - include: packages
    - include: plain-tex
    - include: begin-end-commands
    - include: general-commands
    - include: global-braces
```

**Comment by Awen0121** [comment]
Hi @r-stein ,

Thank you so much for helping.
I changed the match pattern a little bit for identifying optional arguments and inner brace, and it works exactly the way I expect it to now.
```yaml
  main:
    - match: \\todo(?:\[[^\]]*\]){0,1}\{.*\}
      scope: comment.line.todo.latex
    - include: unique-latex
    - include: packages
    - include: plain-tex
    - include: begin-end-commands
    - include: general-commands
    - include: global-braces
```

**Comment by r-stein** [comment]
You are welcome, but if you have nested braces you should better use a context to handle that (otherwise it may match to far):

```yaml
  todo-braces:
    - match: \{
      push:
        - match: \}
          pop: true
        - include: todo-braces
  main:
    - match: \\todo\s*(?:\[[^\]]*\])?
      scope: comment.block.todo.latex
      push:
        - match: \{
          set:
            - meta_scope: comment.block.todo.latex
            - match: \}
              pop: true
            - include: todo-braces
        - match: (?=\S)
          pop: true
    - include: unique-latex
    - include: packages
    - include: plain-tex
    - include: begin-end-commands
    - include: general-commands
    - include: global-braces
```

**Comment by Awen0121** [comment]
Perfect!

**Comment by brchristian** [comment]
@r-stein I have been following this thread in an attempt to make my footnotes lighter in color, but I have found a problem.

When I paste in the code above as written, in particular the `todo-braces` block, I see the following error:

```
Error loading syntax file "Packages/LaTeX/LaTeX.sublime-syntax": Error
trying to parse sublime-syntax: end of map not found in
Packages/LaTeX/LaTeX.sublime-syntax:13:2
```

Here's what the relevant part of my code looks like:

```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: LaTeX
file_extensions:
  - tex
  - ltx
scope: text.tex.latex
contexts:
  prototype:
    - include: comments

 todo-braces:
    - match: \{
      push:
        - match: \}
          pop: true
        - include: todo-braces
  main:
    - match: \\todo\s*(?:\[[^\]]*\])?
      scope: comment.block.todo.latex
      push:
        - match: \{
          set:
            - meta_scope: comment.block.todo.latex
            - match: \}
              pop: true
            - include: todo-braces
        - match: (?=\S)
          pop: true
    - include: unique-latex
    - include: packages
    - include: plain-tex
    - include: begin-end-commands
    - include: general-commands
    - include: global-braces
```

I have attempted to paste in the above code verbatim, but it is not parsing for some reason. Am I doing something wrong here, or has the syntax changed since this thread was written?

Thank you so much for any pointers you might be able to offer!
